Update file posting list for running on moodle 3.11
Uniconnect-corp/kumamoto-moodle-postinglist pull request #1
Opened 2022-02-18 06:25 UTC by thinhnlp

2022-02-18 21:12 UTC, kdemizu requested changes
確認をお願いします。

2022-02-18 21:12 UTC, kdemizu commented on postinglist.php
> +	mdl_user.id = mdl_forum_posts.userid AND
タブスペースが入っているので、他と合わせてスペース2個にしましょう。

2022-02-20 18:24 UTC, kdemizu requested changes
moodle3.11版としてview.phpに追加するコメントの変更をお願いします。

2022-02-20 18:24 UTC, kdemizu commented on postinglist.php
>  Add the following line to mod/forum/view.php just before "echo '</div>';" around L195:
Add the following line to mod/forum/view.php just before "echo '</div>';" around L195:
↓
Add the code below after line 157 "echo $ OUTPUT-> heading (format_string ($ forum-> get_name ()), 2);" in the  mod/forum/view.php file.Compatible with moodle 3.11.
と変更したほうが良いと思いますが、認識は合っていますか？

2022-02-21 05:56 UTC, thinhnlp commented on postinglist.php
>  Add the following line to mod/forum/view.php just before "echo '</div>';" around L195:
はい、ご認識の通りです。
宜しくお願い致します。

2022-02-24 20:16 UTC, kdemizu approved these changes
確認しました。
マージをお願いします。

2022-03-04 03:24 UTC, merged